

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: g4l_dev
      POSTGRES_PASSWORD: P%40ssword!
      POSTGRES_DB: courseGenDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: g4l_dev
      MONGO_INITDB_ROOT_PASSWORD: P%40ssword!
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data: 
  mongodb_data:  
