version: '3.8'  # Specify the Docker Compose version

services:
  postgres:
    image: postgres:latest  # Use the official PostgreSQL image
    environment:
      POSTGRES_USER: g4l_dev
      POSTGRES_PASSWORD: P@ssword!
      POSTGRES_DB: courseGenDB
    ports:
      - "5432:5432"  # Map the container's port to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Define a named volume for PostgreSQL data persistence
