

services:
  postgres:
    image: postgres:latest  # Use the official PostgreSQL image
    environment:
      POSTGRES_USER: g4l_dev
      POSTGRES_PASSWORD: P@ssword!
      POSTGRES_DB: courseGenDB
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Define a named volume for PostgreSQL data persistence
