# Generated by Django 5.2 on 2025-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_gen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='title',
            new_name='courseTitle',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='level',
        ),
        migrations.AddField(
            model_name='prompt',
            name='difficulty',
            field=models.CharField(default='beginner', help_text='The intended difficulty level for the prompt.', max_length=20),
            preserve_default=False,
        ),
    ]
